version: "3.8"

services:
  # 🧠 Base de datos Neo4j
  neo4j:
    image: neo4j:5.10
    container_name: recovery-coach-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"   # Interfaz web (Neo4j Browser)
      - "7687:7687"   # Protocolo Bolt (usado por el backend)
    environment:
      - NEO4J_AUTH=neo4j/recovery123         # Usuario y contraseña (mín. 8 caracteres)
      - NEO4J_dbms_security_auth__minimum__password__length=8
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/init.cypher:/docker-entrypoint-initdb.d/init.cypher

  # ⚙️ Backend FastAPI
  backend:
    build:
      context: ./backend
    container_name: recovery-coach-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
    environment:
      NEO4J_URI: bolt://recovery-coach-neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASS: recovery123
    volumes:
      - ./backend:/app
      - ./datasets:/app/datasets
