version: '3.8'
services:
  neo4j:
    image: neo4j:5.10
    environment:
      NEO4J_AUTH: neo4j/test  # cambiar en producción
    ports:
      - "7474:7474"   # Neo4j Browser
      - "7687:7687"   # Bolt (conexión backend)
    volumes:
      - neo4j_data:/data
      - ./neo4j/init.cypher:/docker-entrypoint-initdb.d/init.cypher:ro

  backend:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - neo4j

volumes:
  neo4j_data:
